        const INVITEES = [
            {s:"abegail-navarro-xaji",f:"Abegail",l:"Navarro"},
            {s:"mark-valles-0y6d",f:"Mark",l:"Valles"},
            {s:"maxine-ava-valles-pbhs",f:"Maxine Ava",l:"Valles"},
            {s:"feliciana-parido-ahxt",f:"Feliciana",l:"Parido"},
            {s:"paul-parido-hv3a",f:"Paul",l:"Parido"},
            {s:"paul-kristian-parido-3zmf",f:"Paul Kristian",l:"Parido"},
            {s:"paul-nicholas-parido-8mdd",f:"Paul Nicholas",l:"Parido"},
            {s:"paul-vincent-parido-4v30",f:"Paul Vincent",l:"Parido"},
            {s:"avianna-keisa-parido-t9nt",f:"Avianna Keisa",l:"Parido"},
            {s:"alwina-dungganon-3w5u",f:"Alwina",l:"Dungganon"},
            {s:"paul-michael-parido-zbik",f:"Paul Michael",l:"Parido"},
            {s:"camille-parido-cidk",f:"Camille",l:"Parido"},
            {s:"catherine-parido-wnnh",f:"Catherine",l:"Parido"},
            {s:"gabriel-valles-j7xv",f:"Gabriel",l:"Valles"},
            {s:"shane-valles-g0fn",f:"Shane",l:"Valles"},
            {s:"maximo-miel-9xuy",f:"Maximo",l:"Miel"},
            {s:"gil-miel-41ib",f:"Gil",l:"Miel"},
            {s:"mhelda-valles-ljh7",f:"Mhelda",l:"Valles"},
            {s:"wilfreda-sasotona-5lxo",f:"Wilfreda",l:"Sasotona"},
            {s:"ernie-sasotona-6qji",f:"Ernie",l:"Sasotona"},
            {s:"carmelita-valles-ujv6",f:"Carmelita",l:"Valles"},
            {s:"joven-macavinta-oh9s",f:"Joven",l:"Macavinta"},
            {s:"reesey-jade-dbdw",f:"Reesey",l:"Jade"},
            {s:"erwin-sasotona-2pcn",f:"Erwin",l:"Sasotona"},
            {s:"cresilda-sasotona-9t84",f:"Cresilda",l:"Sasotona"},
            {s:"wennie-sasotona-azyt",f:"Wennie",l:"Sasotona"},
            {s:"lanie-sasotona-jxep",f:"Lanie",l:"Sasotona"},
            {s:"cerelo-valles-q85j",f:"Cerelo",l:"Valles"},
            {s:"flor-benjamin-sg65",f:"Flor",l:"Benjamin"},
            {s:"dona-benjamin-kxvf",f:"Dona",l:"Benjamin"},
            {s:"brian-garrido-1t2t",f:"Brian",l:"Garrido"},
            {s:"belle-gregorio-ala7",f:"Belle",l:"Gregorio"},
            {s:"mavy-oliva-53lc",f:"Mavy",l:"Oliva"},
            {s:"vince-oliva-58dr",f:"VInce",l:"Oliva"},
            {s:"mederick-parido-c11e",f:"Mederick",l:"Parido"},
            {s:"dianne-enarciso-rtj5",f:"Dianne",l:"Enarciso"},
            {s:"joncim-castro-pht0",f:"Joncim",l:"Castro"},
            {s:"mark-diaz-hl9x",f:"Mark",l:"Diaz"},
            {s:"michael-dizon-psei",f:"Michael",l:"Dizon"},
            {s:"mark-darius-mvih",f:"Mark",l:"Darius"},
            {s:"cedrick-edward-faller-cwi6",f:"Cedrick Edward",l:"Faller"},
            {s:"enrik-espiritu-4ciy",f:"Enrik",l:"Espiritu"},
            {s:"adela-navarro-he7u",f:"Adela",l:"Navarro"},
            {s:"alexander-navarro-r23g",f:"Alexander",l:"Navarro"},
            {s:"dawn-angelique-lopez-dppq",f:"Dawn Angelique",l:"Lopez"},
            {s:"adrian-navarro-0y9d",f:"Adrian",l:"Navarro"},
            {s:"john-anton-lopez-om5i",f:"John Anton",l:"Lopez"},
            {s:"cillian-avery-lopez-gqpk",f:"Cillian Avery",l:"Lopez"},
            {s:"ellaisa-manabat-i7p5",f:"Ellaisa",l:"Manabat"},
            {s:"antipolo-bacares-tb94",f:"Antipolo",l:"Bacares"},
            {s:"marita-diloy-874f",f:"Marita",l:"Diloy"},
            {s:"angelito-diloy-rhoc",f:"Angelito",l:"Diloy"},
            {s:"jocelyn-navarro-n9j2",f:"Jocelyn",l:"Navarro"},
            {s:"meriam-navarro-qp89",f:"Meriam",l:"Navarro"},
            {s:"cherry-lacaste-uzfk",f:"Cherry",l:"Lacaste"},
            {s:"romeo-lacaste-8ut0",f:"Romeo",l:"Lacaste"},
            {s:"imelda-de-mesa-cvs4",f:"Imelda",l:"De Mesa"},
            {s:"mikee-lebaste-f8cg",f:"Mikee",l:"Lebaste"},
            {s:"elejul-manabo-vyie",f:"Elejul",l:"Manabo"},
            {s:"kathleen-feranil-6ivw",f:"Kathleen",l:"Feranil"},
            {s:"aira-janine-lacaste-pvs7",f:"Aira Janine",l:"Lacaste"},
            {s:"john-vincent-lacaste-hzio",f:"John Vincent",l:"Lacaste"},
            {s:"khezea-mae-diloy-ykl1",f:"Khezea Mae",l:"Diloy"},
            {s:"keren-mae-diloy-cq99",f:"Keren Mae",l:"Diloy"},
            {s:"ana-rose-aurio-chj7",f:"Ana Rose",l:"Aurio"},
            {s:"allen-aurio-55nf",f:"Allen",l:"Aurio"},
            {s:"bianca-santos-4zw9",f:"Bianca",l:"Santos"},
            {s:"mikaely-aroen-mejia-xa3k",f:"Mikaely Aroen",l:"Mejia"},
            {s:"camille-silva-x7ee",f:"Camille",l:"Silva"},
            {s:"marie-gay-lontoc-dtjv",f:"Marie Gay",l:"Lontoc"},
            {s:"rachelle-lacaste-zhwj",f:"Rachelle",l:"Lacaste"},
            {s:"gaynord-lamug-r64d",f:"Gaynord",l:"Lamug"},
            {s:"jaira-rivera-pja1",f:"Jaira",l:"Rivera"},
            {s:"lorevil-olaso-wj0t",f:"Lorevil",l:"Olaso"},
            {s:"denden-trinidad-pac5",f:"Denden",l:"Trinidad"},
            {s:"jane-zarzate-6t4u",f:"Jane",l:"Zarzate"},
            {s:"marlo-zarzate-fel6",f:"Marlo",l:"Zarzate"},
            {s:"norma-lopez-246h",f:"Norma",l:"Lopez"},
            {s:"leila-ventura-id25",f:"Leila",l:"Ventura"}
        ];
